### ISSUE TITLE
Completed module 3 assignments (part 1)

### ISSUE THREAD

**Issue by yaozeizei** [ds4owd-001/md-03-assignments-Yaozeizei#1]
@larnsce @mianzg @sskorik01

**Comment by sskorik01** [comment]
Hi Zeyu, 

Congratulations for working through module 3 assignments! You seem to have understood the concepts from the course pretty well. Here are a few details for next time:

1) Make sure to use the right comparison symbol depending if you're asked to use strictly less (<) or less than or equal (<=)

Use `filter()` to create a subset from `penguins` that only contains observations where body mass is **less than or equal** to 2900 g.

```{r}
penguins |> 
  filter(body_mass_g <= 2900)
```

2) When asked to create a column named "id" containing a sequence of values from 1 to the length of the dataframe, instead of using 
```{r}
id = row_number(penguins$species)
```
use the following 
```{r}
id = 1:n()
```
which automatically creates a sequence from 1 to n() which is the length of the dataframe.
